services:
  php:
    build:
      context: ./
    container_name: php
    restart: always
    platform: linux/arm64
    tty: true
    stdin_open: true
    logging:
      driver: "local"
    networks:
      - default
    volumes:
      - ./projects:/projects

networks:
  default:
    driver: bridge
